from .dual_number import DualNumber
eps = DualNumber(0.,1.)
from .elementary_functions import sin
from .elementary_functions import cos
from .elementary_functions import tan
from .elementary_functions import exp
from .elementary_functions import log
from .elementary_functions import power
from .elementary_functions import sqrt
from .elementary_functions import arccos
from .elementary_functions import arcsin
from .elementary_functions import arctan
from .elementary_functions import sinh
from .elementary_functions import cosh
from .elementary_functions import tanh
from .elementary_functions import arcsinh
from .elementary_functions import arccosh
from .elementary_functions import erf
from .utils.gradient_descent import update
from .utils.gradient_descent import zero_grad